name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT || 22 }}
          timeout: 120s
          script: |
            echo "Connected successfully"
            cd /root/apps/bts-guru-daemon
            git checkout main
            git stash
            git pull origin main
            docker compose down
            docker compose up -d
            composer ssh-php artisan migrate
            composer ssh-php sh services start
